name: 'Runtime Variable Substitution Override Input Parameter'
description: 'Convert input parameters to runtime-overrides semicolon delimited list of kvp'
inputs:
  input-params:
    description: 'Input parameters JSON'
    required: true
    type: string
    default: ''
outputs:
  input-params:
    description: 'Output rvs delimited list of kvp'
    value: ${{ steps.kvp-values.outputs.input-params }}
  
runs:
  using: "composite"
  steps:
    - name: List all workflow inputs in KVP format
      id: kvp-values
      run: |
      shell: bash
  