name: "Fastlane action"
description: "This GitHub Execute PreScript And Fastlane by assuming Fastlane Repository present in working Dir\
for testing purposes."
inputs:
   working_repo:
     required: true
     type: string
   fastlane_repo:
     required: true
     type: string
   lane_name:
     required: true
     type: string
   env_name:
     required: true
     type: string
   script_path:
     required: false
     type: string
   gitPATToken:
     required: true
     type: string

runs:
  using: 'composite'

  steps:
    - name: "Checkout Soure code"
      uses: actions/checkout@main
      with:
        repository: ${{ inputs.fastlane_repo }}
        path: scripts
        token: ${{ inputs.gitPATToken }}

    - name: 'Script folder created in project dir and moving files from scripts to project dir'
      shell: bash
      run: |
       mv -v scripts/*  ${{ inputs.working_repo }} 
       
    - name: "Run PreScript"
      shell: bash
      run: |
       chmod 777  ${{ inputs.script_path }} 
       ${{ inputs.script_path }} 

    - name: "Run Fastlane"
      shell: bash
      run: |
        bundle install
        fastlane ios ${{ inputs.lane_name }} 
